version: '3.9'

services:
  app:
    build: .
    container_name: cinema-backend
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cinemadb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

      # External APIs
      - TMDB_API_KEY=your_tmdb_api_key
      - GOOGLE_CLIENT_ID=your_google_client_id
      - STRIPE_API_KEY=your_stripe_api_key
      - STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret
      - STRIPE_PRODUCT_ID=your_stripe_product_id
      - STRIPE_PRICE_ID=your_stripe_price_id
      - EMAIL_USERNAME=your_email@gmail.com
      - EMAIL_PASSWORD=your_email_password

    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: cinema-db-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cinemadb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-cinema-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-cinema-data: